---
title: "GLM-LOGÍSTIC"
author: "Diego Rodríguez"
date: "2024-06-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# ==============================================================================
# GLM - Logístic 
# ==============================================================================
library(e1071) # Necesario para la validación cruzada
library(tidyverse)
library(caret)
library(FactoMineR)

# ==============================================================================
# Rutas: 
path <- "D:\\UNI\\TFG\\"
DATADIR <- paste0(path, "data\\")

# ==============================================================================
# Leemos los datos
datos <- get(load(paste0(DATADIR, "datosNivelPartido.RData"))); rm(dconAgrupado)

# ==============================================================================
# Eliminamos la variable equipos que no tenemos
datos[, "equipos"] <- NULL
datos[, "tiempoJuego"] <- NULL
datos[, "generos"] <- as.factor(datos[, "generos"])

# ==============================================================================
# c. Dividir los datos en conjunto de entrenamiento y prueba:
set.seed(123)  # Para reproducibilidad
trainIndex <- createDataPartition(datos$informe, p = 0.8, 
                                  list = FALSE, 
                                  times = 1)
dataTrain <- datos[trainIndex,]
dataTest <- datos[-trainIndex,]


# ==============================================================================
# d. Entrenar el modelo de regresión logística:
## Entrenar el modelo de regresión logística
model <- glm(informe ~ ., data = dataTrain, family = binomial)

# Resumen del modelo
summary(model)

modeloStep <- step(model, direction = "backward")

# ==============================================================================
# e. Hacer predicciones y calcular probabilidades:
# Hacer predicciones en el conjunto de prueba
predicciones <- predict(modeloStep, newdata = dataTest, type = "response")

# Ver las probabilidades predichas
print(predicciones)

# Convertir probabilidades a clases
pred_clases <- ifelse(predicciones > 0.5, 1, 0)

# Matriz de confusión
(matriz_confusion <- confusionMatrix(factor(pred_clases), factor(dataTest$informe)))

fourfoldplot(matriz_confusion$table, color = c("#CC6666", "#99CC99"), conf.level = 0, margin = 1, main = "Confusion Matrix")

library(ggplot2)

# Convertir la matriz de confusión en un data frame para ggplot2
conf_df <- as.data.frame(matriz_confusion$table)
names(conf_df) <- c("Predicted", "Actual", "Freq")

# Crear el gráfico de la matriz de confusión con ggplot2
ggplot(conf_df, aes(x = Actual, y = Predicted, fill = Freq)) +
  geom_tile() +
  scale_fill_gradient(low = "steelblue1", high = "red") +
  geom_text(aes(label = Freq), vjust = 1) +
  labs(title = "Confusion Matrix", x = "Actual", y = "Predicted") +
  theme_minimal()
```